CREATE TABLE IF NOT EXISTS `%s` (
 `gps_id` int(11) NOT NULL AUTO_INCREMENT,
  `gps_name` varchar(32) DEFAULT NULL,
  `gps_host` varchar(32) DEFAULT NULL,
  `gps_type` varchar(10) DEFAULT NULL,
  `gps_utc_coord` int(11) DEFAULT NULL,
  `gps_status` char(1) DEFAULT NULL,
  `gps_latitude` varchar(16) DEFAULT NULL,
  `gps_ns` char(1) DEFAULT NULL,
  `gps_longitude` varchar(16) DEFAULT NULL,
  `gps_ew` char(1) DEFAULT NULL,
  `gps_speed` float DEFAULT NULL,
  `gps_course` float DEFAULT NULL,
  `gps_utc_date` int(11) DEFAULT NULL,
  `gps_mvd` float DEFAULT NULL,
  `gps_mv` char(1) DEFAULT NULL,
  `gps_cs` varchar(100) DEFAULT NULL,
  `gps_msg_ori` varchar(1024) DEFAULT NULL,
  `gps_time` timestamp NULL DEFAULT NULL,
  `gps_latitude_real` double DEFAULT NULL,
  `gps_longitude_real` double DEFAULT NULL,
  `gps_odometer` double DEFAULT NULL,
  `gps_workhour` int(11) DEFAULT NULL,
  `gps_geofence` varchar(255) DEFAULT NULL,
  `gps_last_road_type` varchar(100) DEFAULT NULL,
  `gps_speed_limit` int(4) DEFAULT NULL,
  `gps_speed_status` tinyint(1) DEFAULT NULL,
  `gps_notif` tinyint(1) DEFAULT '0',
  `gps_alert` varchar(100) DEFAULT '',
  `gps_view` int(11) DEFAULT '0',
  `gps_inserttime` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`gps_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

